home/urls.py
from django.urls import path
from home.views import landing, login_user, logout_user, register, landing_logged, render_test, show_data_json,create_testimonial


app_name = 'home'

urlpatterns = [
    path('', landing, name='landing'),
    path('logged/', landing_logged, name='landing_logged'),
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('json/', show_data_json, name='show_data_json'),
    path('add/', create_testimonial, name='add'),
    path('logout/', logout_user, name='logout'),
    path('test/', render_test, name='test'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('parallel_sessions/', include('parallel_sessions.urls')),
    path('submission/', include('submission.urls')),
    path('authors/', include('authors.urls')),
    path('events/', include('events.urls')),
    path('speakers/', include('speakers.urls')),
]

# TODO: Implement Routings Here

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Testimonial(models.Model):
    username = models.CharField(max_length=255, default="Guest")
    content = models.TextField()
    institute = models.CharField(max_length=255)

home/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import logout
from home.models import Testimonial
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers

@login_required(login_url='/login/')
def landing_logged(request):
    testimonials = Testimonial.objects.all()
    context = {
        'user' : request.user,
        'items': testimonials,
    }   
    return render(request, "index2.html", context)

def landing(request):
    testimonials = Testimonial.objects.all()
    context = {
        'user' : request.user,
        'items': testimonials,
    }   
    return render(request, "index.html", context)

def render_test(request):
    testimonials = Testimonial.objects.all()
    context = {
        'user' : request.user,
        'items': testimonials,
    }   
    return render(request, "test_index.html", context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home:landing_logged')
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('home:login')

    context = {'form':form}
    return render(request, 'register.html', context)

@login_required(login_url='/login/')
def create_testimonial(request):
    if request.method == "POST":
        username = request.POST.get('username')
        content = request.POST.get('content')
        institute = request.POST.get('institute')
        if content != "" and username != "" and institute != "":
            data = Testimonial.objects.create(username=username, content=content, institute=institute)
            return JsonResponse({
                    "pk": data.id,
                    "fields": {
                        "username": data.username,
                        "content": data.content,
                        "institute": data.institute,
                    },
                },
                status=200,
            )
        else:
            messages.info(request, 'Please fill the username/content/institute!')

@login_required(login_url='/login/')
def logout_user(request):
    logout(request)
    return redirect('home:login')

def show_data_json(request):
    data = Testimonial.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

home/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<body>
  <section class="relative flex flex-wrap lg:h-screen lg:items-center">
    <div class="w-full px-4 py-12 sm:px-6 sm:py-16 lg:w-1/2 lg:px-8 lg:py-24">
      <div class="mx-auto max-w-lg text-center">
        <h1 class="text-2xl font-bold sm:text-3xl">Welcome!</h1>
  
        <p class="mt-4 text-gray-500">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Et libero nulla
          eaque error neque ipsa culpa autem, at itaque nostrum!
        </p>
      </div>
  
      <form action="" method="POST"class="mx-auto mt-8 mb-0 max-w-md space-y-4">
        {% csrf_token %}
        <div>
          <label for="username" class="sr-only">Username</label>
  
          <div class="relative">
            <input
              type="username"
              name="username"
              class="w-full rounded-lg border-gray-200 p-4 pr-12 text-sm shadow-sm"
              placeholder="Enter username"
            />
          </div>
        </div>
  
        <div>
          <label for="password" class="sr-only">Password</label>
          <div class="relative">
            <input
              type="password"
              name="password"
              class="w-full rounded-lg border-gray-200 p-4 pr-12 text-sm shadow-sm"
              placeholder="Enter password"
            />

          </div>
        </div>
  
        <div class="flex items-center justify-between">
          <p class="text-sm text-gray-500">
            No account?
            <a href="{% url 'home:register' %}" class="underline">Sign up</a>
            or
            <a href="{% url 'home:landing' %}" class="underline">Go back</a>
          </p>
  
          <button
            type="submit"
            class="ml-3 inline-block rounded-lg bg-[#412D7E] px-4 py-2 md:px-5 md:py-3 text-sm font-medium text-white"
          >
          <input type="submit" class="text-sm" value="">Sign in
          </button>
        </div>
      </form>
      {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
      {% endif %}   
    </div>
  
    <div class="relative h-64 w-full sm:h-96 lg:h-full lg:w-1/2">
      <img
        alt="Welcome"
        src="{% static 'home/login.jpeg' %}"
        class="absolute inset-0 h-full w-full object-cover"
      />
    </div>
  </section>
</body>
  
{% endblock content %}

home/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}


<div class="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-lg">
      <h1 class="text-center text-2xl font-bold text-[#412D7E] sm:text-3xl">
        Get started today
      </h1>
  
      <p class="mx-auto mt-2 max-w-md text-center text-gray-500">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati sunt
        dolores deleniti inventore quaerat mollitia?
      </p>
  
      <form action="" method="POST" class="mt-4 mb-0 space-y-2 rounded-lg p-4 shadow-2xl">
        {% csrf_token %}
        <p class="text-2xl mb-4 text-center justify-center font-semibold">Register your account!</p>
        <div class="flex w-full my-4 border-t border-black"></div>
        {% for field in form %}
            <div class="relative mt-2">
                <p class="">{{ field.label }} <br> {{ field }}</p> 
    
                {% for error in field.errors %}
                    <small style="color: red">{{ error }}</small>
                {% endfor %}
            </div>
        {% endfor %}
        <button class="block w-full rounded-lg bg-[#412D7E] px-5 py-3 text-sm font-medium text-white" 
        type="submit">Register</button>
        <div class="flex items-center justify-center">
            <p class="text-sm text-gray-500">
              Already have an account?
              <a href="{% url 'home:login' %}" class="underline">Sign in</a>
              or
              <a href="{% url 'home:landing' %}" class="underline">Go back</a>
            </p>
    </div>
  </div>
  
</form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
        </ul>
    {% endif %}

</div>

{% endblock content %}